# Provenance: generated by ai_testing/generate_tests.py (model claude-opus-5-5) on 2026-10-05
# from testdata/openapi_snapshot.json. Reviewed by a human, run green, then promoted here.
# Three of these tests exposed DEF-106 (see docs/04_defect_management.md).
"""Additional API regression coverage for /api/submissions.

Adds tests the existing suite does not cover:
- authentication (401) on every operation, and that rejected calls have no side effects
- title and text length boundaries
- validation of missing, mistyped and malformed input
- Unicode and encoding round-trips
- idempotency of DELETE, and interactions between create, list, get and delete
- path ids that are unusual or URL-encoded
"""
import uuid

import pytest

from testdata.factory import SubmissionFactory

pytestmark = [pytest.mark.api, pytest.mark.regression]

# Setting a header to None in a per-request override removes the
# session-level header. That gives an unauthenticated request through
# the same `api` session.
NO_AUTH = {"X-API-Key": None}
BAD_AUTH = {"X-API-Key": "invalid-" + uuid.uuid4().hex}


def _text_of_length(n):
    """Return deterministic word-like text of exactly n chars.

    The text has no leading or trailing whitespace, so server-side
    trimming cannot change its length.
    """
    base = "abcdefghi "
    s = (base * (n // len(base) + 2))[:n]
    if s.endswith(" "):
        s = s[:-1] + "z"
    assert len(s) == n
    return s


@pytest.fixture
def make_submission(api, base_url):
    """Create submissions through the API and delete them on teardown."""
    created_ids = []

    def _make(**overrides):
        payload = SubmissionFactory.build(**overrides)
        resp = api.post(f"{base_url}/api/submissions", json=payload)
        if resp.status_code == 201:
            created_ids.append(resp.json()["id"])
        return resp

    yield _make

    for sid in created_ids:
        api.delete(f"{base_url}/api/submissions/{sid}")


# --------------------------------------------------------------------------
# Authentication
# --------------------------------------------------------------------------


@pytest.mark.parametrize("headers", [NO_AUTH, BAD_AUTH], ids=["missing_key", "invalid_key"])
def test_list_submissions_without_valid_key_returns_401(api, base_url, headers):
    resp = api.get(f"{base_url}/api/submissions", headers=headers)
    assert resp.status_code == 401


@pytest.mark.parametrize("headers", [NO_AUTH, BAD_AUTH], ids=["missing_key", "invalid_key"])
def test_create_submission_without_valid_key_returns_401(api, base_url, headers):
    resp = api.post(
        f"{base_url}/api/submissions",
        json=SubmissionFactory.build(),
        headers=headers,
    )
    assert resp.status_code == 401


@pytest.mark.parametrize("headers", [NO_AUTH, BAD_AUTH], ids=["missing_key", "invalid_key"])
def test_get_existing_submission_without_valid_key_returns_401(api, base_url, created_submission, headers):
    resp = api.get(f"{base_url}/api/submissions/{created_submission['id']}", headers=headers)
    assert resp.status_code == 401


@pytest.mark.parametrize("headers", [NO_AUTH, BAD_AUTH], ids=["missing_key", "invalid_key"])
def test_delete_existing_submission_without_valid_key_returns_401(api, base_url, make_submission, headers):
    sid = make_submission().json()["id"]
    resp = api.delete(f"{base_url}/api/submissions/{sid}", headers=headers)
    assert resp.status_code == 401


def test_unauthenticated_delete_leaves_submission_retrievable(api, base_url, make_submission):
    sid = make_submission().json()["id"]
    api.delete(f"{base_url}/api/submissions/{sid}", headers=NO_AUTH)
    assert api.get(f"{base_url}/api/submissions/{sid}").status_code == 200


def test_unauthenticated_create_does_not_persist_submission(api, base_url):
    marker = f"unauth-{uuid.uuid4().hex}"
    api.post(
        f"{base_url}/api/submissions",
        json=SubmissionFactory.build(title=marker),
        headers=NO_AUTH,
    )
    items = api.get(f"{base_url}/api/submissions").json()["items"]
    assert not any(i["title"] == marker for i in items)


# --------------------------------------------------------------------------
# Length boundaries
# --------------------------------------------------------------------------


@pytest.mark.parametrize(
    "overrides",
    [
        {"title": "t"},
        {"text": _text_of_length(20)},
        {"text": _text_of_length(20000)},
    ],
    ids=["title_1_char", "text_20_chars", "text_20000_chars"],
)
def test_lengths_at_inclusive_boundaries_are_accepted(make_submission, overrides):
    resp = make_submission(**overrides)
    assert resp.status_code == 201, resp.text


@pytest.mark.parametrize(
    "overrides, bad_field",
    [
        ({"title": ""}, "title"),
        ({"text": _text_of_length(19)}, "text"),
        ({"text": _text_of_length(20001)}, "text"),
    ],
    ids=["title_empty", "text_19_chars", "text_20001_chars"],
)
def test_lengths_just_outside_boundaries_are_rejected_naming_field(make_submission, overrides, bad_field):
    resp = make_submission(**overrides)
    assert resp.status_code == 400
    body = resp.json()
    assert body["error"] == "validation_failed"
    assert bad_field in body["fields"]


# --------------------------------------------------------------------------
# Required fields, types and malformed input
# --------------------------------------------------------------------------


@pytest.mark.parametrize("missing_field", ["author", "text"])
def test_missing_required_field_is_rejected_naming_field(api, base_url, missing_field):
    payload = SubmissionFactory.build()
    payload.pop(missing_field)
    resp = api.post(f"{base_url}/api/submissions", json=payload)
    assert resp.status_code == 400
    assert missing_field in resp.json()["fields"]


@pytest.mark.parametrize(
    "field, bad_value",
    [
        ("title", 12345),
        ("title", None),
        ("author", None),
        ("author", {"name": "x"}),
        ("text", ["not", "a", "string", "but", "a", "list", "of", "words"]),
        ("text", None),
    ],
    ids=["title_int", "title_null", "author_null", "author_object", "text_list", "text_null"],
)
def test_wrongly_typed_field_is_rejected_naming_field(api, base_url, field, bad_value):
    payload = SubmissionFactory.build()
    payload[field] = bad_value
    resp = api.post(f"{base_url}/api/submissions", json=payload)
    assert resp.status_code == 400
    assert field in resp.json()["fields"]


def test_malformed_json_body_returns_400(api, base_url):
    resp = api.post(
        f"{base_url}/api/submissions",
        data='{"title": "unterminated',
        headers={"Content-Type": "application/json"},
    )
    assert resp.status_code == 400


def test_rejected_submission_is_not_persisted(api, base_url):
    marker = f"rejected-{uuid.uuid4().hex}"
    payload = SubmissionFactory.build(author=marker, title="")
    assert api.post(f"{base_url}/api/submissions", json=payload).status_code == 400
    items = api.get(f"{base_url}/api/submissions").json()["items"]
    assert not any(i.get("author") == marker for i in items)


# --------------------------------------------------------------------------
# Encoding
# --------------------------------------------------------------------------


@pytest.mark.parametrize("char", ["é", "漢", "ж"], ids=["latin_accent", "cjk", "cyrillic"])
def test_title_of_200_multibyte_chars_is_accepted(make_submission, char):
    resp = make_submission(title=char * 200)
    assert resp.status_code == 201, resp.text


def test_unicode_fields_round_trip_unchanged_through_get(api, base_url, make_submission):
    title = "Ünïcödé — 論文 «test» 'quotes' \"double\" & <tags>"
    author = "Zoë O'Brien-Łukasiewicz 李"
    sid = make_submission(title=title, author=author).json()["id"]
    body = api.get(f"{base_url}/api/submissions/{sid}").json()
    assert (body["title"], body["author"]) == (title, author)


# --------------------------------------------------------------------------
# Idempotency and interactions between endpoints
# --------------------------------------------------------------------------


def test_second_delete_of_same_submission_returns_404(api, base_url, make_submission):
    sid = make_submission().json()["id"]
    assert api.delete(f"{base_url}/api/submissions/{sid}").status_code == 204
    assert api.delete(f"{base_url}/api/submissions/{sid}").status_code == 404


def test_deleted_submission_is_absent_from_list(api, base_url, make_submission):
    sid = make_submission().json()["id"]
    api.delete(f"{base_url}/api/submissions/{sid}")
    items = api.get(f"{base_url}/api/submissions").json()["items"]
    assert not any(i["id"] == sid for i in items)


def test_identical_payload_posted_twice_creates_distinct_ids(api, base_url, make_submission):
    payload = SubmissionFactory.build()
    first = make_submission(**payload).json()
    second = make_submission(**payload).json()
    assert first["id"] != second["id"]


def test_deleting_one_submission_does_not_affect_another(api, base_url, make_submission):
    keep_id = make_submission().json()["id"]
    drop_id = make_submission().json()["id"]
    api.delete(f"{base_url}/api/submissions/{drop_id}")
    assert api.get(f"{base_url}/api/submissions/{keep_id}").status_code == 200


def test_listed_item_matches_get_by_id_representation(api, base_url, make_submission):
    created = make_submission().json()
    items = api.get(f"{base_url}/api/submissions").json()["items"]
    listed = next(i for i in items if i["id"] == created["id"])
    fetched = api.get(f"{base_url}/api/submissions/{created['id']}").json()
    assert {k: fetched[k] for k in listed} == listed


# --------------------------------------------------------------------------
# Unusual path ids
# --------------------------------------------------------------------------


@pytest.mark.parametrize(
    "weird_id",
    ["0", "-1", "null", "x" * 1024, "%E6%BC%A2", "id%20with%20spaces"],
    ids=["zero", "negative", "literal_null", "very_long", "encoded_unicode", "encoded_spaces"],
)
def test_get_with_unusual_nonexistent_id_returns_404(api, base_url, weird_id):
    assert api.get(f"{base_url}/api/submissions/{weird_id}").status_code == 404


@pytest.mark.parametrize(
    "weird_id",
    ["0", "-1", "x" * 1024, "%E6%BC%A2"],
    ids=["zero", "negative", "very_long", "encoded_unicode"],
)
def test_delete_with_unusual_nonexistent_id_returns_404(api, base_url, weird_id):
    assert api.delete(f"{base_url}/api/submissions/{weird_id}").status_code == 404
